### ISSUE TITLE
Typo3 10.4.23: error downloading pdf file from frontend page

### ISSUE THREAD

**Issue by gbartolucci** [t3brightside/form_pdf#2]
I'm using form_pdf version 1.1.2 . The link inside the ConfirmationWithLink.html page for download pdf file after submit the form doesn't work. When I click on the link I have this error in typo3's log file:
TypeError: Return value of TYPO3\CMS\Core\Http\Dispatcher::dispatch() must be an instance of Psr\Http\Message\ResponseInterface, null returned in <root_directory>/typo3_src-10.4.23/typo3/sysext/core/Classes/Http/Dispatcher.php:53
This because the method EXT:form_pdf/Classes/Ajax/PdfResponse->processRequest() doesn't return an instance of ResponseInterface

**Comment by t3brightside** [comment]
@gbartolucci thanks for the feedback. At this very moment sadly there's no time to get on the bottom of it but some work will be done on the extension in next month hopefully.

**Comment by gbartolucci** [comment]
I tried to give a solution for the problem with a patch request. I'm not very expert with gihub, so excuse me if I did some errors for publish the patch

**Comment by t3brightside** [comment]
@gbartolucci Thanks! Took forever but implemented finally now.
