### ISSUE TITLE
Ext. Upgrade to TYPO3 v.11

### ISSUE THREAD

**Issue by Steppo-pxl** [t3brightside/form_pdf#4]
Hello,

is an upgrade of the extension for TYPO3 11 planned?
And if so, is it foreseeable when it will be finished?

Thanks.

**Comment by t3brightside** [comment]
@Steppo-pxl There will be. There's some work done on it, but takes it's time as it seems. Probably by the end of the year.

**Comment by t3brightside** [comment]
@Steppo-pxl actually took another look into it. There's the updated dev version now, you can give it a try. TYPO3 11 only. Confirmation page link works. E-mail attach part is not tested yet.

**Comment by t3brightside** [comment]
New version 1.2.0 is available, ready for TYPO3 11.

**Comment by ineswillenbrock** [comment]
Hi, will you push the 1.2 to the TER?

**Comment by t3brightside** [comment]
Hey @ineswillenbrock, no there will not be any more TER packages as it's another one to maintain, different from composer package.

**Comment by ineswillenbrock** [comment]
That said, this one won't work if I download it and load it into a classical installed TYPO3? Or would it?

**Comment by t3brightside** [comment]
No, it wouldn't.

**Comment by ineswillenbrock** [comment]
Thanks, for your time to clarify.
But that's actually frustrating for me as I could have used this extension.
I do appreciate your time, don't understand me wrong, and if you don't use classic installations anymore: you don't need the TER version.

**Comment by t3brightside** [comment]
Free software only goes so far... Composer is the recommended way for TYPO3 these days. It would be as frustrating for me to do it for free where's I have no use for it myself :)  There's always an option for paid support and as it's open source anybody with the skill can do it.

**Comment by ineswillenbrock** [comment]
If I added Classic/TER Support, would you be willing to integrate it? At least into github? No need to have two extensions.

As I said, if you don't need it, why invest time into it? Someone has to pay: and most likely the one, that uses it :) (And if you'd rather do it yourself: can I come back to this and request a quote (via email)?)
