### ISSUE TITLE
Upgrade to T3 v11

### ISSUE THREAD

**Issue by Steppo-pxl** [t3brightside/form_pdf#5]
Thank you for the upgrade.

When I try to install the extension via Composer, I get the following messages:

.. composer require t3brightside/form-pdf
Using version ^1.3 for t3brightside/form-pdf
./composer.json has been updated
Running composer update t3brightside/form-pdf
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires t3brightside/form-pdf ^1.3 -> satisfiable by t3brightside/form-pdf[1.3.0, 1.3.1].
    - t3brightside/form-pdf[1.3.0, ..., 1.3.1] require typo3/cms-core ^11.5 -> found typo3/cms-core[v11.5.0, ..., v11.5.16] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - friendsoftypo3/phpstan-typo3 is locked to version 0.5.0 and an update of this package was not requested.
    - friendsoftypo3/phpstan-typo3 0.5.0 requires typo3/cms-core ^10.4 || 11.0.*@dev -> found typo3/cms-core[v10.4.0, ..., v10.4.32, v11.0.0] but these were not loaded, likely because it conflicts with another require.
  Problem 3
    - typo3/testing-framework is locked to version 6.6.2 and an update of this package was not requested.
    - typo3/testing-framework 6.6.2 requires typo3/cms-backend 10.*.*@dev || 11.*.*@dev -> found typo3/cms-backend[v10.0.0, ..., v10.4.32, v11.0.0, ..., v11.5.16] but these were not loaded, likely because it conflicts with another re                                                                                    quire.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require t3brightside/form-pdf:*" to figure out if any version is installable, or "composer require t3brightside/form-pdf:^2.1" if you kn                                                                                    ow which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by t3brightside** [comment]
TYPO3 10.4 is no more supported
