### ISSUE TITLE
Cant see PDF-finisher in backend.

### ISSUE THREAD

**Issue by Steppo-pxl** [t3brightside/form_pdf#6]
TYPO3 v. 11.5.16
pdf_form 1.3.1

**Comment by t3brightside** [comment]
My first guess is to follow install instructions.
Include the main template and Flush TYPO3 and PHP Cache.

Any help?

**Comment by Steppo-pxl** [comment]
Done, i cant see the finisher in the backend.

**Comment by t3brightside** [comment]
It's hard to say really as it's not sufficient information for finding the problem.

**Comment by Steppo-pxl** [comment]
Hi,

I totally understand that, but unfortunately no errors are displayed for me. I am currently working with the latest TYPO3 version and with the PDF Ext. from Github. 
TYPO3 caches, install_tool etc. were checked, emptied...

Unfortunately I don't have an error. 
Oh and as a theme I use the Bootstrap_Package.

**Comment by steppo79** [comment]
Hello,

I was able to solve the problem.
The magic was trying it via Composer Mode.

Thanks for your help.
